import { data, currentTab, sortMode } from './state.js';

export const CARD_DESCRIPTIONS = {
  1: 'Pre-TimeSkip Monkey D. Luffy',
  2: 'Post-TimeSkip Monkey D. Luffy',
  3: 'Afro-Luffy',
  4: 'Nightmare-Luffy',
  5: 'Gear 2nd',
  6: 'Gear 3rd',
  7: 'Gear 4th',
  8: 'Gear 5th',
  9: 'Eyecatcher Luffy',
  10: 'Pre-TimeSkip Zoro',
  11: 'Post-TimeSkip Zoro',
  12: 'Eyecatcher Zoro',
  13: 'Pre-TimeSkip Nami',
  14: 'Post-TimeSkip Nami',
  15: 'Eyecatcher Nami',
  16: 'Pre-TimeSkip Usopp',
  17: 'Post-TimeSkip Usopp',
  18: 'Eyecatcher Usopp',
  19: 'Pre-TimeSkip Sanji',
  20: 'Post-TimeSkip Sanji',
  21: 'Eyecatcher Sanji',
  22: 'Pre-TimeSkip Chopper',
  23: 'Post-TimeSkip Chopper',
  24: 'Eyecatcher Chopper',
  25: 'Pre-TimeSkip Nico Robin',
  26: 'Post-TimeSkip Nico Robin',
  27: 'Eyecatcher Nico Robin',
  28: 'Pre-TimeSkip Franky',
  29: 'Post-TimeSkip Franky',
  30: 'Eyecatcher Franky',
  31: 'Pre-TimeSkip Brook',
  32: 'Post-TimeSkip Brook',
  33: 'Eyecatcher Brook',
  34: 'Pre-TimeSkip Jimbe',
  35: 'Post-TimeSkip Jimbe',
  36: 'Eyecatcher Jimbe',
  37: 'Zeff',
  38: 'Kaya',
  39: 'Coby',
  40: 'Dr Kureha',
  41: 'Vivi',
  42: 'Karoo',
  43: 'Pedro',
  44: 'Carrot',
  45: 'Yamato',
  46: 'Shanks',
  47: 'Ben Beckman',
  48: 'Yasopp',
  49: 'Rebecca',
  50: 'Bartolomeo',
  51: 'Leo',
  52: 'Ace',
  53: 'Whitebeard',
  54: 'Marco',
  55: 'Arlong',
  56: 'Hody Jones',
  57: 'Enel',
  58: 'Crocodile',
  59: 'Mr1/Daz Bones',
  60: 'Bon Clay',
  61: 'Mr3/Galdino',
  62: 'Buggy',
  63: 'Caeser Clown',
  64: 'Monkey D. Luffy',
  65: 'Monkey D. Luffy',
  66: 'Monkey D. Luffy',
  67: 'Monkey D. Luffy',
  68: 'Monkey D. Luffy',
  69: 'Monkey D. Luffy',
  70: 'Monkey D. Luffy',
  71: 'Monkey D. Luffy',
  72: 'Monkey D. Luffy',
  73: 'Monkey D. Luffy',
  74: 'Monkey D. Luffy',
  75: 'Monkey D. Luffy',
  76: 'Monkey D. Luffy',
  77: 'Monkey D. Luffy',
  78: 'Monkey D. Luffy',
  79: 'Monkey D. Luffy',
  80: 'Monkey D. Luffy',
  81: 'Monkey D. Luffy',
  82: 'Monkey D. Luffy',
  83: 'Monkey D. Luffy',
  84: 'Monkey D. Luffy',
  85: 'Monkey D. Luffy',
  86: 'Monkey D. Luffy',
  87: 'Monkey D. Luffy',
  88: 'Monkey D. Luffy',
  89: 'Monkey D. Luffy',
  90: 'Monkey D. Luffy',
  91: 'Monkey D. Luffy',
  92: 'Monkey D. Luffy',
  93: 'Monkey D. Luffy',
  94: 'Monkey D. Luffy',
  95: 'Monkey D. Luffy',
  96: 'Monkey D. Luffy',
  97: 'Monkey D. Luffy',
  98: 'Monkey D. Luffy',
  99: 'Monkey D. Luffy',
  100: 'Monkey D. Luffy',
  101: 'Monkey D. Luffy',
  102: 'Monkey D. Luffy',
  103: 'Monkey D. Luffy',
  104: 'Monkey D. Luffy',
  105: 'Monkey D. Luffy',
  106: 'Monkey D. Luffy',
  107: 'Monkey D. Luffy',
  108: 'Monkey D. Luffy',
  109: 'Monkey D. Luffy',
  110: 'Monkey D. Luffy',
  111: 'Monkey D. Luffy',
  112: 'Monkey D. Luffy',
  113: 'Monkey D. Luffy',
  114: 'Monkey D. Luffy',
  115: 'Monkey D. Luffy',
  116: 'Monkey D. Luffy',
  117: 'Monkey D. Luffy',
  118: 'Monkey D. Luffy',
  119: 'Monkey D. Luffy',
  120: 'Monkey D. Luffy',
  121: 'Monkey D. Luffy',
  122: 'Monkey D. Luffy',
  123: 'Monkey D. Luffy',
  124: 'Monkey D. Luffy',
  125: 'Monkey D. Luffy',
  126: 'Monkey D. Luffy',
  127: 'Monkey D. Luffy',
  128: 'Monkey D. Luffy',
  129: 'Monkey D. Luffy',
  130: 'Monkey D. Luffy',
  131: 'Monkey D. Luffy',
  132: 'Monkey D. Luffy',
  133: 'Monkey D. Luffy',
  134: 'Monkey D. Luffy',
  135: 'Monkey D. Luffy',
  136: 'Monkey D. Luffy',
  137: 'Monkey D. Luffy',
  138: 'Monkey D. Luffy',
  139: 'Monkey D. Luffy',
  140: 'Monkey D. Luffy',
  141: 'Monkey D. Luffy',
  142: 'Monkey D. Luffy',
  143: 'Monkey D. Luffy',
  144: 'Monkey D. Luffy',
  145: 'Monkey D. Luffy',
  146: 'Monkey D. Luffy',
  147: 'Monkey D. Luffy',
  148: 'Monkey D. Luffy',
  149: 'Monkey D. Luffy',
  150: 'Monkey D. Luffy',
  151: 'Monkey D. Luffy',
  152: 'Monkey D. Luffy',
  153: 'Monkey D. Luffy',
  154: 'Monkey D. Luffy',
  155: 'Monkey D. Luffy',
  156: 'Monkey D. Luffy',
  157: 'Monkey D. Luffy',
  158: 'Monkey D. Luffy',
  159: 'Monkey D. Luffy',
  160: 'Monkey D. Luffy',
  161: 'Monkey D. Luffy',
  162: 'Monkey D. Luffy',
  163: 'Monkey D. Luffy',
  164: 'Monkey D. Luffy',
  165: 'Monkey D. Luffy',
  166: 'Monkey D. Luffy',
  167: 'Monkey D. Luffy',
  168: 'Monkey D. Luffy',
  169: 'Monkey D. Luffy',
  170: 'Monkey D. Luffy',
  171: 'Monkey D. Luffy',
  172: 'Monkey D. Luffy',
  173: 'Monkey D. Luffy',
  174: 'Monkey D. Luffy',
  175: 'Monkey D. Luffy',
  176: 'Monkey D. Luffy',
  177: 'Monkey D. Luffy',
  178: 'Monkey D. Luffy',
  179: 'Monkey D. Luffy',
  180: 'Monkey D. Luffy',
  181: 'Monkey D. Luffy',
  182: 'Monkey D. Luffy',
  183: 'Monkey D. Luffy',
  184: 'Monkey D. Luffy',
  185: 'Monkey D. Luffy',
  186: 'Monkey D. Luffy',
  187: 'Monkey D. Luffy',
  188: 'Monkey D. Luffy',
  189: 'Monkey D. Luffy',
  190: 'Monkey D. Luffy',
  191: 'Monkey D. Luffy',
  192: 'Monkey D. Luffy',
  193: 'Monkey D. Luffy',
  194: 'Monkey D. Luffy',
  195: 'Monkey D. Luffy',
  196: 'Monkey D. Luffy',
  197: 'Monkey D. Luffy',
  198: 'Monkey D. Luffy',
  199: 'Monkey D. Luffy',
  200: 'Monkey D. Luffy',
  // συμπληρώνεις όποτε θες μέχρι 200
};

export function calculateGlobalTotal() {
  let sum = 0;

  for (let i = 1; i <= 200; i++) {
    if (currentTab === 'Total') {
      if (data.Marira[i]) sum += data.Marira[i].count || 1;
      if (data.Soriris[i]) sum += data.Soriris[i].count || 1;
    } else {
      const entry = data[currentTab][i];
      if (entry) sum += entry.count || 1;
    }
  }

  return sum;
}

export function getSortedItems() {
  const items = [];

  for (let i = 1; i <= 200; i++) {
    let count = 0;

    if (currentTab === 'Total') {
      if (data.Marira[i]) count += data.Marira[i].count || 1;
      if (data.Soriris[i]) count += data.Soriris[i].count || 1;
    } else {
      const entry = data[currentTab][i];
      if (entry) count = entry.count || 1;
    }

    items.push({ number: i, count });
  }

  // 🔹 SORT LOGIC
  if (sortMode === 'count') {
    items.sort((a, b) => b.count - a.count || a.number - b.number);
  } else {
    items.sort((a, b) => a.number - b.number);
  }

  return items;
}
